# Generated by Django 4.1.7 on 2023-10-04 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NintendoNetworkID',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('nnid', models.CharField(max_length=16, verbose_name='Nintendo Network ID')),
                ('mii_hash', models.CharField(max_length=13)),
                ('mii_data', models.TextField()),
                ('nickname', models.CharField(max_length=11)),
                ('pid', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miiapp.nintendonetworkid')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miiapp.nintendonetworkid')),
            ],
        ),
    ]
