# Generated by Django 4.1.7 on 2023-10-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nintendonetworkid',
            options={'verbose_name': 'Nintendo Network ID', 'verbose_name_plural': 'Nintendo Network ID'},
        ),
    ]
