# Generated by Django 4.1.7 on 2023-10-07 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miiapp', '0002_alter_nintendonetworkid_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='nintendonetworkid',
            name='archived_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 7, 10, 58, 38, 261385, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='nintendonetworkid',
            name='refreshed_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 7, 10, 58, 38, 261490, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='nintendonetworkid',
            name='mii_hash',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='nintendonetworkid',
            name='nnid',
            field=models.CharField(max_length=16, unique=True, verbose_name='Nintendo Network ID'),
        ),
        migrations.AlterField(
            model_name='nintendonetworkid',
            name='pid',
            field=models.IntegerField(unique=True),
        ),
    ]
