# Generated by Django 4.1.7 on 2023-10-07 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miiapp', '0003_nintendonetworkid_archived_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockList',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('nnid', models.CharField(max_length=16, unique=True, verbose_name='Nintendo Network ID')),
            ],
        ),
        migrations.AlterField(
            model_name='nintendonetworkid',
            name='archived_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 7, 14, 6, 57, 953359, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='nintendonetworkid',
            name='refreshed_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 7, 14, 6, 57, 953391, tzinfo=datetime.timezone.utc)),
        ),
    ]
