# Generated by Django 4.1.7 on 2023-10-07 15:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miiapp', '0006_rename_blocklist_blockednnid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nintendonetworkid',
            name='refresher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='refresher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nintendonetworkid',
            name='archived_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 7, 15, 49, 8, 471103, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='nintendonetworkid',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nintendonetworkid',
            name='refreshed_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 7, 15, 49, 8, 471135, tzinfo=datetime.timezone.utc)),
        ),
    ]
