# Generated by Django 4.1.7 on 2023-10-07 16:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miiapp', '0007_nintendonetworkid_refresher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nintendonetworkid',
            name='archived_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 7, 16, 30, 26, 811474, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='nintendonetworkid',
            name='refreshed_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 7, 16, 30, 26, 811502, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
